{
 "title": "Codex",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "API Upload/Download", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "codexApiUploads_total" }
   ]
  },
  {
   "title": "Downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "codexApiDownloads_total" }
   ]
  },
  { "title": "Local Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    { "expr": "codexRepostoreBlocks" }
   ]
  },
  {
   "title": "Bytes reserved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "codexRepostoreBytesReserved" }
   ]
  },
  {
   "title": "Bytes used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "codexRepostoreBytesUsed" }
   ]
  },
  { "title": "Network Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    { "expr": "libp2p_peers" }
   ]
  },
  {
   "title": "Routing table nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "targets": [
    { "expr": "routing_table_nodes" }
   ]
  },
  { "title": "Block Exchange", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Blocks sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "codexBlockExchangeBlocksSent_total"
    }
   ]
  },
  {
   "title": "Blocks received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "codexBlockExchangeBlocksReceived_total"
    }
   ]
  },
  {
   "title": "WantHave lists sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "codexBlockExchangeWantHaveListsSent_total"
    }
   ]
  },
  {
   "title": "WantBlock lists sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
   "targets": [
    {
     "expr": "codexBlockExchangeWantBlockListsSent_total"
    }
   ]
  },
  {
   "title": "WantHave lists received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "codexBlockExchangeWantHaveListsReceived_total"
    }
   ]
  },
  {
   "title": "WantBlock lists received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
   "targets": [
    {
     "expr": "codexBlockExchangeWantBlockListsReceived_total"
    }
   ]
  },
  { "title": "Purchases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Pending",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    { "expr": "codexPurchasesPending_total" }
   ]
  },
  {
   "title": "Submitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "targets": [
    { "expr": "codexPurchasesSubmitted_total" }
   ]
  },
  {
   "title": "Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "targets": [
    { "expr": "codexPurchasesStarted_total" }
   ]
  },
  {
   "title": "Finished",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "targets": [
    { "expr": "codexPurchasesFinished_total" }
   ]
  },
  {
   "title": "Failed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "targets": [
    { "expr": "codexPurchasesFailed_total" }
   ]
  },
  {
   "title": "Cancelled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "targets": [
    { "expr": "codexPurchasesCancelled_total" }
   ]
  },
  {
   "title": "Unknown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "targets": [
    { "expr": "codexPurchasesUnknown_total" }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "targets": [
    { "expr": "codexPurchasesError_total" }
   ]
  }
 ]
}