dotnet run \
    --deploy-name=codex-continuous-test-deployment \
    --kube-config=/opt/kubeconfig.yaml \
    --kube-namespace=codex-continuous-tests \
    --deploy-file=codex-deployment.json \
    --nodes=5 \
    --validators=3 \
    --log-level=Trace \
    --storage-quota=2048 \
    --storage-sell=1024 \
    --min-price=1024 \
    --max-collateral=1024 \
    --max-duration=3600000 \
    --block-ttl=180 \
    --block-mi=120 \
    --block-mn=10000 \
    --metrics=1 \
    --check-connect=1
