name: Docker - Runner


on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
    paths:
      - docker/Dockerfile
      - docker/docker-entrypoint.sh
      - .github/workflows/docker-runner.yml
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: codex-storage/github-actions/.github/workflows/docker-reusable.yml@master
    with:
      docker_file: docker/Dockerfile
      dockerhub_repo: codexstorage/cs-codex-dist-tests
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit
