name: Docker - KeyMaker


on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
    paths:
      - 'Tools/KeyMaker/**'
      - 'Framework/**'
      - 'ProjectPlugins/**'
      - .github/workflows/docker-keymaker.yml
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: codex-storage/github-actions/.github/workflows/docker-reusable.yml@master
    with:
      docker_file: Tools/KeyMaker/docker/Dockerfile
      dockerhub_repo: codexstorage/codex-keymaker
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit
