name: Docker - Discord Bot


on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
    paths:
      - 'Tools/BiblioTech/**'
      - '!Tools/BiblioTech/docker/docker-compose.yaml'
      - 'Framework/**'
      - 'ProjectPlugins/**'
      - .github/workflows/docker-discordbot.yml
  workflow_dispatch:


jobs:
  build-and-push:
    name: Build and Push
    uses: codex-storage/github-actions/.github/workflows/docker-reusable.yml@master
    with:
      docker_file: Tools/BiblioTech/docker/Dockerfile
      dockerhub_repo: codexstorage/codex-discordbot
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit
